service: sso-bypass

frameworkVersion: '2'
useDotenv: true
provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  sso-bypass:
    handler: build/index.main

plugins:
  - serverless-dotenv-plugin